package me.abhigya.pit.database

import java.sql.*
import java.util.*
import java.util.concurrent.Executor

object NullConnection : Connection {
    
    override fun <T : Any> unwrap(iface: Class<T>): T {
        throw UninitializedException
    }

    override fun isWrapperFor(iface: Class<*>): Boolean {
        throw UninitializedException
    }

    override fun close() {
        throw UninitializedException
    }

    override fun createStatement(): Statement {
        throw UninitializedException
    }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int): Statement {
        throw UninitializedException
    }

    override fun createStatement(resultSetType: Int, resultSetConcurrency: Int, resultSetHoldability: Int): Statement {
        throw UninitializedException
    }

    override fun prepareStatement(sql: String): PreparedStatement {
        throw UninitializedException
    }

    override fun prepareStatement(sql: String, resultSetType: Int, resultSetConcurrency: Int): PreparedStatement {
        throw UninitializedException
    }

    override fun prepareStatement(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int
    ): PreparedStatement {
        throw UninitializedException
    }

    override fun prepareStatement(sql: String, autoGeneratedKeys: Int): PreparedStatement {
        throw UninitializedException
    }

    override fun prepareStatement(sql: String, columnIndexes: IntArray): PreparedStatement {
        throw UninitializedException
    }

    override fun prepareStatement(sql: String, columnNames: Array<out String>): PreparedStatement {
        throw UninitializedException
    }

    override fun prepareCall(sql: String): CallableStatement {
        throw UninitializedException
    }

    override fun prepareCall(sql: String, resultSetType: Int, resultSetConcurrency: Int): CallableStatement {
        throw UninitializedException
    }

    override fun prepareCall(
        sql: String,
        resultSetType: Int,
        resultSetConcurrency: Int,
        resultSetHoldability: Int
    ): CallableStatement {
        throw UninitializedException
    }

    override fun nativeSQL(sql: String): String {
        throw UninitializedException
    }

    override fun setAutoCommit(autoCommit: Boolean) {
        throw UninitializedException
    }

    override fun getAutoCommit(): Boolean {
        throw UninitializedException
    }

    override fun commit() {
        throw UninitializedException
    }

    override fun rollback() {
        throw UninitializedException
    }

    override fun rollback(savepoint: Savepoint) {
        throw UninitializedException
    }

    override fun isClosed(): Boolean {
        throw UninitializedException
    }

    override fun getMetaData(): DatabaseMetaData {
        throw UninitializedException
    }

    override fun setReadOnly(readOnly: Boolean) {
        throw UninitializedException
    }

    override fun isReadOnly(): Boolean {
        throw UninitializedException
    }

    override fun setCatalog(catalog: String) {
        throw UninitializedException
    }

    override fun getCatalog(): String {
        throw UninitializedException
    }

    override fun setTransactionIsolation(level: Int) {
        throw UninitializedException
    }

    override fun getTransactionIsolation(): Int {
        throw UninitializedException
    }

    override fun getWarnings(): SQLWarning {
        throw UninitializedException
    }

    override fun clearWarnings() {
        throw UninitializedException
    }

    override fun getTypeMap(): MutableMap<String, Class<*>> {
        throw UninitializedException
    }

    override fun setTypeMap(map: MutableMap<String, Class<*>>) {
        throw UninitializedException
    }

    override fun setHoldability(holdability: Int) {
        throw UninitializedException
    }

    override fun getHoldability(): Int {
        throw UninitializedException
    }

    override fun setSavepoint(): Savepoint {
        throw UninitializedException
    }

    override fun setSavepoint(name: String): Savepoint {
        throw UninitializedException
    }

    override fun releaseSavepoint(savepoint: Savepoint) {
        throw UninitializedException
    }

    override fun createClob(): Clob {
        throw UninitializedException
    }

    override fun createBlob(): Blob {
        throw UninitializedException
    }

    override fun createNClob(): NClob {
        throw UninitializedException
    }

    override fun createSQLXML(): SQLXML {
        throw UninitializedException
    }

    override fun isValid(timeout: Int): Boolean {
        throw UninitializedException
    }

    override fun setClientInfo(name: String, value: String) {
        throw UninitializedException
    }

    override fun setClientInfo(properties: Properties) {
        throw UninitializedException
    }

    override fun getClientInfo(name: String): String {
        throw UninitializedException
    }

    override fun getClientInfo(): Properties {
        throw UninitializedException
    }

    override fun createArrayOf(typeName: String, elements: Array<out Any>): java.sql.Array {
        throw UninitializedException
    }

    override fun createStruct(typeName: String, attributes: Array<out Any>): Struct {
        throw UninitializedException
    }

    override fun setSchema(schema: String) {
        throw UninitializedException
    }

    override fun getSchema(): String {
        throw UninitializedException
    }

    override fun abort(executor: Executor) {
        throw UninitializedException
    }

    override fun setNetworkTimeout(executor: Executor, milliseconds: Int) {
        throw UninitializedException
    }

    override fun getNetworkTimeout(): Int {
        throw UninitializedException
    }
    
}

object UninitializedException : SQLException("Uninitialized")