-- Player Table
CREATE TABLE IF NOT EXISTS `players` (
    `UUID`      VARCHAR(36) NOT NULL,
    `NAME`      VARCHAR(16) NOT NULL,
    `BALANCE`   INT NOT NULL DEFAULT 0,
    `BOUNTY`    INT NOT NULL DEFAULT 0,
    `LEVEL`     INT NOT NULL DEFAULT 0,
    `PRESTIGE`  INT NOT NULL DEFAULT 0,
    `RENOWN`    INT NOT NULL DEFAULT 0
);

-- Stats Table
CREATE TABLE IF NOT EXISTS `stats` (
    `UUID`                  VARCHAR(36) NOT NULL,
    `BOW_DAMAGE_TAKEN`      FLOAT NOT NULL DEFAULT 0,
    `DAMAGE_TAKEN`          FLOAT NOT NULL DEFAULT 0,
    `DEATHS`                INT NOT NULL DEFAULT 0,
    `MELEE_DAMAGE_TAKEN`    FLOAT NOT NULL DEFAULT 0,
    `BLOCKS_BROKEN`         INT NOT NULL DEFAULT 0,
    `BLOCKS_PLACED`         INT NOT NULL DEFAULT 0,
    `CHAT_MESSAGES`         INT NOT NULL DEFAULT 0,
    `FISHING_RODS_LAUNCHED` INT NOT NULL DEFAULT 0,
    `GOLDEN_APPLES_EATEN`   INT NOT NULL DEFAULT 0,
    `JUMPS_INTO_PIT`        INT NOT NULL DEFAULT 0,
    `LAVA_BUCKETS_EMPTIED`  INT NOT NULL DEFAULT 0,
    `LEFT_CLICKS`           INT NOT NULL DEFAULT 0,
    `ARROW_HITS`            INT NOT NULL DEFAULT 0,
    `ARROW_SHOTS`           INT NOT NULL DEFAULT 0,
    `ASSISTS`               INT NOT NULL DEFAULT 0,
    `BOW_DAMAGE_DEALT`      FLOAT NOT NULL DEFAULT 0,
    `LAUNCHES`              INT NOT NULL DEFAULT 0,
    `DAMAGE_DEALT`          FLOAT NOT NULL DEFAULT 0,
    `HIGHEST_STREAK`        INT NOT NULL DEFAULT 0,
    `KILLS`                 INT NOT NULL DEFAULT 0,
    `MELEE_DAMAGE_DEALT`    FLOAT NOT NULL DEFAULT 0,
    `SWORD_HITS`            INT NOT NULL DEFAULT 0,
    `GOLD_EARNED`           INT NOT NULL DEFAULT 0,
    `GOLDEN_HEADS_EATEN`    INT NOT NULL DEFAULT 0
);